# Step 1: Choose correct IP source
map $http_cf_connecting_ip $geoip2_lookup_ip {
    ""      $remote_addr;
    default $http_cf_connecting_ip;
}

# Step 2: Use that for ASN lookup
geoip2 /etc/nginx/GeoLite2-ASN.mmdb {
    $geoip2_asn_org source=$geoip2_lookup_ip autonomous_system_organization;
}

# Step 2: Use that for ASN lookup
geoip2 /etc/nginx/GeoLite2-Country.mmdb {
    $geoip2_country_code source=$geoip2_lookup_ip country iso_code;
    $geoip2_country_name source=$geoip2_lookup_ip country names en;
}
