#log_format geoip_debug '$http_cf_connecting_ip - $geoip2_asn_org [$time_local] "$request"';
#log_format geoip_debug '$geoip2_lookup_ip - $geoip2_asn_org [$time_local] "$request"';
log_format geoip_debug '$remote_addr - $geoip2_lookup_ip - $geoip2_asn_org - $geoip2_country_code [$time_local] "$request"';


