- name: Update package cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - git
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Clone Payload Server repository
  git:
    repo: "https://github.com/hegusung/payload_server.git"
    dest: "/opt/payload_server"
    version: main
    update: yes

- name: Template .env file
  ansible.builtin.template:
    src: payload_server.env.j2
    dest: "/opt/payload_server/.env"
    owner: root
    group: root
    mode: "0640"

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: 
  shell: docker compose up -d --build
  args:
    chdir: "/opt/payload_server"


