- name: Update the instance
  apt:
    update_cache: yes

- name: Install OpenVPN
  apt:
    name: openvpn
    state: present

- name: Upload OpenVPN configuration file
  copy:
    src: files/{{ certificate_name }}.ovpn  # Path to the file on the control node
    dest: /etc/openvpn/client/client.conf  # Path to the destination on the remote node
    mode: '0644'

- name: Start and enable OpenVPN service
  service:
    name: openvpn-client@client  # Ensure the service matches your OpenVPN setup (e.g., openvpn@<config_name>)
    state: started
    enabled: yes 

- name: Check OpenVPN connection
  shell: ip addr show tap0
  register: openvpn_ip_info
  failed_when: "'tap0' not in openvpn_ip_info.stdout"

- name: Parse OpenVPN-assigned IP
  set_fact:
    openvpn_ip: "{{ openvpn_ip_info.stdout | regex_search('inet ([0-9.]+)/', '\\1') }}"

- name: Display OpenVPN IP address
  debug:
    msg: "The OpenVPN-assigned IP address is {{ openvpn_ip }}"

- name: Save the OpenVPN IP
  set_fact:
    node_ovpn_ip: "{{ openvpn_ip[0] }}"

