- name: Install the RedELK redirectors clients
  hosts: host
  gather_facts: no
  become: yes
  tasks:
    - name: Install and configure RedELK redirectors
      include_role:
        name: redelk
        tasks_from: setup_redelk_redirectors.yml
